la_smart_dining_radar:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: "{{ 'service-account' if env_var('GCP_CREDENTIALS_PATH', '') else 'oauth' }}"
      keyfile: "{{ env_var('GCP_CREDENTIALS_PATH', '') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_MART') }}"
      location: US
      threads: 4
